databases:
  - name: smartticket-postgres
    plan: free
    databaseName: ticketdb
    user: admin

services:
  - type: web
    name: smartticket-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartticket-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: CORS_ORIGINS
        value: "https://smartticket-frontend.onrender.com"
      - key: MISTRAL_API_KEY
        sync: false
      - key: EMBED_MODEL
        value: mistral-embed

  - type: web
    name: smartticket-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://smartticket-backend.onrender.com"
